export enum MetadataKey {
  COLLECTION = 'COLLECTION',
  EMBEDDED = 'EMBEDDED',
  INDEXES = 'INDEXES',
  VALIDATORS = 'VALIDATORS',
  FIELDS = 'FIELDS',
  PROPS = 'PROPS',
  MIDDLEWARES = 'MIDDLEWARES',
  PLUGINS = 'PLUGINS'
}

export default MetadataKey
